#include "course/CourseSpriteMgr.h"
#include "course/ProfileId.h"

using namespace ProfileId;


const u16 CourseSpriteMgr::spriteToProfileIds[] =
{
    AutoScrollTag,                // 0
    WaterStream,                  // 1
    WaterBubbleTag,               // 2
    Bakubaku,                     // 3
    Burner,                       // 4
    BurnerDown,                   // 5
    BurnerLeft,                   // 6
    BurnerUp,                     // 7
    Basabasa,                     // 8
    Battan,                       // 9
    BeltSwitch,                   // 10
    WaterStreamBg,                // 11
    BgActorLava,                  // 12
    BgActorPoison,                // 13
    BgActorCloud,                 // 14
    BgActorWater,                 // 15
    Birikyu,                      // 16
    BirikyuRotParent,             // 17
    ChangeBlock,                  // 18
    ActorBlockFunka,              // 19
    ActorBlockHatenaCap,          // 20
    ActorBlockJump,               // 21
    NextGotoBlock,                // 22
    ObjClearBlock,                // 23
    ActorBlockPata,               // 24
    ActorBlockPataNigeru,         // 25
    RouletBlock,                  // 26
    ActorBlockShock,              // 27
    ActorBlockShockPairChild,     // 28
    Bomhei,                       // 29
    KokoopaDemo,                  // 30
    BoomerangBros,                // 31
    FireBros,                     // 32
    HammerBros,                   // 33
    HimanBros,                    // 34
    Bubble,                       // 35
    BubbleArch,                   // 36
    BuiBuiDemo,                   // 37
    BuiBuiWheel,                  // 38
    BuiBuiFloor,                  // 39
    BurnerBlock,                  // 40
    BurnerBlockDown,              // 41
    BurnerBlockLeft,              // 42
    BurnerBlockUp,                // 43
    BurnerCross,                  // 44
    BurnerLine,                   // 45
    BurnerLineDown,               // 46
    BurnerLineLeft,               // 47
    BurnerLineUp,                 // 48
    TarzanChain,                  // 49
    TarzanChainMgr,               // 50
    Chorobon,                     // 51
    CheckPointFlag,               // 52
    CenterSwing,                  // 53
    CenterRotation,               // 54
    ActorCoin,                    // 55
    ActorCoinBubble,              // 56
    FunkaCoin,                    // 57
    FunsuiCoin,                   // 58
    ActorCoinAngle,               // 59
    ActorCoinPairChild,           // 60
    RedCoin,                      // 61
    RedCoinAngle,                 // 62
    BigPileLeft,                  // 63
    BigPileRight,                 // 64
    DokanMorton,                  // 65
    CannonPipe,                   // 66
    LudwigCannonPipe,             // 67
    WakiDokan,                    // 68
    DoorNormal,                   // 69
    DoorCastle,                   // 70
    DoorClose,                    // 71
    DoorKoopa,                    // 72
    DoorObake,                    // 73
    DoorSwitch,                   // 74
    DoorToride,                   // 75
    BigDossun,                    // 76
    Dossun,                       // 77
    FireBar,                      // 78
    FireCoinJet,                  // 79
    FireCoin,                     // 80
    FireCoinChanger,              // 81
    FireSnake,                    // 82
    FishBone,                     // 83
    FlagSwitchChange,             // 84
    FlagSwitchIf,                 // 85
    FlagSwitchTag,                // 86
    FlagSwitchContinue,           // 87
    FlagSwitchCreateAfter,        // 88
    Fugumannen,                   // 89
    WakiFugumannen,               // 90
    Gamaguchi,                    // 91
    Garigari,                     // 92
    Gasagoso,                     // 93
    GateOneway,                   // 94
    Gesso,                        // 95
    GessoKodure,                  // 96
    GoalPole,                     // 97
    GroupId,                      // 98
    Hanachan,                     // 99
    ActorBlockHatenaAngle,        // 100
    ActorBlockHatenaPairChild,    // 101
    Iggy,                         // 102
    ItemHouseMgr,                 // 103
    JugemCloud,                   // 104
    WakiJugem,                    // 105
    Jumpdai,                      // 106
    WireRail,                     // 107
    GasaNet,                      // 108
    KanbanArrow,                  // 109
    Karon,                        // 110
    BigKaron,                     // 111
    KazandanMgr,                  // 112
    Keronpa,                      // 113
    WoodBox,                      // 114
    KillerHoudai,                 // 115
    KaitenHoudai,                 // 116
    MagnumKillerHoudai,           // 117
    Killer,                       // 118
    MagnumKiller,                 // 119
    KinokoLiftUpDown,             // 120
    LiftSlideKinoko,              // 121
    LiftSlideKinokoSync,          // 122
    TrplnKinoko,                  // 123
    KinokoLift,                   // 124
    Koopa,                        // 125
    KoopaDemo,                    // 126
    BossFire,                     // 127
    KoopaBone,                    // 128
    KoopaLastBone,                // 129
    KoopaLast,                    // 130
    KoopaLastBlock,               // 131
    KoopaLastLift,                // 132
    BossShutterKoopa,             // 133
    KoopaFloor,                   // 134
    Kuribo,                       // 135
    KuriboBone,                   // 136
    BeansKuribo,                  // 137
    PataKuribo,                   // 138
    KuriboTower,                  // 139
    Crow,                         // 140
    Larry,                        // 141
    Lemmy,                        // 142
    LemmySwitch,                  // 143
    LiftRideHmove,                // 144
    LiftRideVmove,                // 145
    LiftLine,                     // 146
    LiftM,                        // 147
    LiftMoveOn,                   // 148
    LiftRideMoveUpDown,           // 149
    LiftSeeSaw,                   // 150
    LiftTenbin,                   // 151
    LiftRailGhost,                // 152
    LiftWaki,                     // 153
    LiftWaterWheel,               // 154
    Ludwig,                       // 155
    MaxUeLeft,                    // 156
    MaxUeRight,                   // 157
    Met,                          // 158
    TogeMet,                      // 159
    LrStopDw,                     // 160
    LrStopUp,                     // 161
    Morton,                       // 162
    NetNokonokoLR,                // 163
    NetNokonokoUD,                // 164
    Nokonoko,                     // 165
    PairObjParent,                // 166
    DokanPakkunDown,              // 167
    DokanFirePakkunDown,          // 168
    DokanFirePakkunLeft,          // 169
    DokanFirePakkunRight,         // 170
    DokanFirePakkunUp,            // 171
    DokanBonePakkunUp,            // 172
    DokanBonePakkunLeft,          // 173
    DokanBonePakkunRight,         // 174
    JimenPakkun,                  // 175
    JimenBigPakkun,               // 176
    JimenFirePakkun,              // 177
    JimenBigFirePakkun,           // 178
    JimenBonePakkun,              // 179
    JimenBigBonePakkun,           // 180
    DokanPakkunLeft,              // 181
    DokanPakkunRight,             // 182
    DokanPakkunUp,                // 183
    ParaBomhei,                   // 184
    Patapata,                     // 185
    PatapataRotParent,            // 186
    RailPolyChild,                // 187
    RailPolyParent,               // 188
    ObjPol,                       // 189
    ObjPolChecker,                // 190
    ObjPolDesert,                 // 191
    ObjPolCastle,                 // 192
    ObjPolSea,                    // 193
    Pukupuku,                     // 194
    PukupukuBig,                  // 195
    PukupukuCoin,                 // 196
    PukupukuJump,                 // 197
    WakiPukupukuJump,             // 198
    PukupukuRotParent,            // 199
    Togepuku,                     // 200
    WakiPukupuku,                 // 201
    RailLimit,                    // 202
    ActorBlockRengaAngle,         // 203
    ActorBlockRengaPairChild,     // 204
    RedRing,                      // 205
    YellowRing,                   // 206
    Rock,                         // 207
    RockBig,                      // 208
    TarzanRope,                   // 209
    TightRope,                    // 210
    Roy,                          // 211
    RoyWall,                      // 212
    Sanbo,                        // 213
    ScrollView,                   // 214
    ShipCannon,                   // 215
    BossShutter,                  // 216
    SnakeBlock,                   // 217
    SnakeBlockSync,               // 218
    CollectionCoin,               // 219
    CollectionCoinAngle,          // 220
    SwitchBikkuriButton,          // 221
    ActorBlockBikkuriSwitch,      // 222
    SwitchHatenaButton,           // 223
    ActorBlockHatenaSwitch,       // 224
    SwitchPbutton,                // 225
    ActorBlockPSwitch,            // 226
    Barrel,                       // 227
    Teresa,                       // 228
    BigTeresa,                    // 229
    TeresaRotParent,              // 230
    TeresaMega,                   // 231
    Togezo,                       // 232
    ReverseTogezo,                // 233
    TogeTekkyu,                   // 234
    TogeTekkyuBig,                // 235
    TogeTekkyuMega,               // 236
    WakiTogeTekkyu,               // 237
    WakiTogeTekkyuSync,           // 238
    TarzanIvy,                    // 239
    Unira,                        // 240
    UniraKaiten,                  // 241
    Uzu,                          // 242
    WallMove,                     // 243
    WanwanPile,                   // 244
    Wendy,                        // 245
    WendyWater,                   // 246
    YukaBane,                     // 247
    LiftMoveOnGhost,              // 248
    RotBlockNormal,               // 249
    RotBlockChecker,              // 250
    ItemTreasureBox,              // 251
    ItemObj,                      // 252
    LarryYuka,                    // 253
    LiftRideVmoveTotem,           // 254
    KoopaHead,                    // 255
    NukiAtariKun,                 // 256
    LiftRailBone,                 // 257
    KoopaLastDemo,                // 258
    ActorBlockUnbrokenAngle,      // 259
    BuiBuiDemoRoy,                // 260
    BuiBuiDemoIggy,               // 261
    BuiBuiDemoWendy,              // 262
    BuiBuiDemoMorton,             // 263
    BuiBuiDemoLudwig,             // 264
    BuiBuiDemoNone,               // 265
    KoopaClown,                   // 266
    ActorBlockHatenaLong,         // 267
    ObjPolLava,                   // 268
    TreasureShip,                 // 269
    SnowBall,                     // 270
    SnowBallBig,                  // 271
    PeachCageDemo,                // 272
    RouletCoinBlock,              // 273
    ActorBlockGoldPata,           // 274
    ActorBlockHatenaLongChika,    // 275
    ActorBlockHatenaLongLava,     // 276
    BeltSwitchNormal,             // 277
    ActorBlockAssist,             // 278
    LemmyBallCastle,              // 279
    TimerClock,                   // 280
    LiftRailIce,                  // 281
    ObjPolGhost,                  // 282
    ObjPolLarry,                  // 283
    LiftChandelierS,              // 284
    LiftChandelierM,              // 285
    LiftChandelierL,              // 286
    DoorKinopio,                  // 287
    PlayerBigRes,                 // 288
    TrplnKinokoCastle,            // 289
    WireRailSmall,                // 290
    WireRailMiddle,               // 291
    KanbanWarp,                   // 292
    PunchBlock,                   // 293
    CannonWarp,                   // 294
    BattanRes,                    // 295
    Kinopio,                      // 296
    WireLineSlide,                // 297
    HakushuKun,                   // 298
    LemmyStatue,                  // 299
    ActorCoinHakusyu,             // 300
    KoopaLastLiftMgr,             // 301
    MoonCoin,                     // 302
    MoonCoinAngle,                // 303
    KoopaLastFire,                // 304
    RailPolyIce,                  // 305
    KoopaHead2,                   // 306
    ObjPolIseki,                  // 307
    ObjPolSand,                   // 308
    DorifuAnime,                  // 309
    KoopaLastLiftUp,              // 310
    ActorCoinNagareboshi,         // 311
    NoStockItem,                  // 312
    ObjPolKazari,                 // 313
    LiftMIseki,                   // 314
    PeachEnding,                  // 315
    EnvStarTag,                   // 316
    EnvSporeTag,                  // 317
    ObjPolToride,                 // 318
    EndingBoss,                   // 319
    LiftRail,                     // 320
    KinokoLiftSnow,               // 321
    GarigariBig,                  // 322
    EndingBird,                   // 323
    ObjNukiBlock,                 // 324
    NoItemBalloon,                // 325

    // Custom sprites go below

};

const u32 CourseSpriteMgr::spriteCount = sizeof(CourseSpriteMgr::spriteToProfileIds) / sizeof(CourseSpriteMgr::spriteToProfileIds[0]);
